conventions:
  - path: ejball/ejball-common/conventions/ejball-dotnet-package
  - path: ejball/ejball-common/conventions/ejball-dotnet-app-workflows
    settings:
      release-artifact-path: ./artifacts/publish/ToggleResolution/release_win-x86/ToggleResolution.exe

pull-request:
  reviewers:
    - ejball