name: Release

on:
  push:
    tags:
    - '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]'

env:
  DOTNET_NOLOGO: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

defaults:
  run:
    shell: pwsh

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v6
    - name: Install .NET
      uses: actions/setup-dotnet@v5
    - name: Package
      run: ./build.ps1 package
    - name: Create zip
      run: Compress-Archive ./artifacts/publish/ToggleResolution/release_win-x86/ToggleResolution.exe ${{ github.event.repository.name }}.zip
    - name: Create release
      uses: softprops/action-gh-release@v2
      with:
        files: ./${{ github.event.repository.name }}.zip
